apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app
        image: <your-dockerhub-username>/<your-app-name>:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
