apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-web
  template:
    metadata:
      labels:
        app: ticketing-web
    spec:
      containers:
      - name: ticketing-web
        image: acrproject.azurecr.io/ticketing-web:latest  # ACR 이미지 주소
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret  # your-app에서 사용된 동일한 시크릿 이름
